# -*- coding: utf-8 -*-
"""3rd Program LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FlSIGJEwxu43C8NL7xuRn4zjJQwIs1MU
"""

import huggingface_hub
from huggingface_hub import hf_hub_download
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

# Load pre-trained DistilBERT model fine-tuned for sentiment analysis
model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

# Changed sentence (positive sentiment)
text = "I like listening to music"

# Tokenize input
inputs = tokenizer(text, return_tensors="pt")

# Perform inference
with torch.no_grad():
    outputs = model(**inputs)

# Get predicted label
label = torch.argmax(outputs.logits).item()

# Print sentiment
print("Sentiment:", "POSITIVE" if label == 1 else "NEGATIVE")