# -*- coding: utf-8 -*-
"""Wild life LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N7_zUsb1pHaDV7SuFM6MA7AUEtIXC52j
"""

import numpy as np
from tensorflow.keras.applications.resnet50 import (
    ResNet50,
    preprocess_input,
    decode_predictions
)
from tensorflow.keras.preprocessing import image

# Detect environment
try:
    from google.colab import files
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

# Load model
model = ResNet50(weights="imagenet")

# Species keyword groups
DOG_KEYWORDS = [
    "dog", "retriever", "shepherd", "terrier", "bulldog",
    "poodle", "husky", "rottweiler", "doberman", "pitbull"
]

CAT_KEYWORDS = [
    "cat", "siamese", "persian", "tabby", "egyptian mau"
]

BIRD_KEYWORDS = [
    "bird", "parrot", "macaw", "cockatoo", "sparrow",
    "hen", "peacock", "eagle", "owl", "duck", "goose",
    "canary", "goldfinch", "hummingbird", "flamingo",
    "robin", "pelican", "kingfisher", "penguin"
]

CONFIDENCE_THRESHOLD = 0.20


def identify_species(img_path, top_n=5):
    """Identify dog, cat, bird, or other from an image"""
    try:
        img = image.load_img(img_path, target_size=(224, 224))
    except Exception as e:
        print(f"❌ Could not load image: {e}")
        return

    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = preprocess_input(img_array)

    preds = model.predict(img_array, verbose=0)
    decoded = decode_predictions(preds, top=top_n)[0]

    print(f"\n🔍 Top {top_n} predictions:\n")

    detected = False

    for _, label, confidence in decoded:
        label_clean = label.lower().replace("_", " ")
        print(f"- {label_clean} ({confidence:.2f})")

        if confidence < CONFIDENCE_THRESHOLD:
            continue

        if any(k in label_clean for k in DOG_KEYWORDS):
            print(f"\n🐶 Detected: Dog ({label_clean}, {confidence:.2f})")
            detected = True
            break

        if any(k in label_clean for k in CAT_KEYWORDS):
            print(f"\n🐱 Detected: Cat ({label_clean}, {confidence:.2f})")
            detected = True
            break

        if any(k in label_clean for k in BIRD_KEYWORDS):
            print(f"\n🐦 Detected: Bird ({label_clean}, {confidence:.2f})")
            detected = True
            break

    if not detected:
        print("\n❓ Species detected: Other / Unknown\n")


# -------------------------------
# IMAGE INPUT HANDLING
# -------------------------------
if IN_COLAB:
    print("📁 Upload an image")
    uploaded = files.upload()
    for filename in uploaded:
        print(f"\nProcessing {filename}")
        identify_species(filename)
else:
    img_path = input("📁 Enter image path: ").strip()
    identify_species(img_path)